# Generated by Django 5.0.3 on 2024-07-07 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('komentar', models.TextField(blank=True, null=True)),
                ('tanggal_review', models.DateTimeField(auto_now_add=True)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lapanganfutsal')),
            ],
        ),
    ]
